    <br /><br /><br /><br />
    <br /><br /><br /><br />
    <br /><br /><br /><br />
    <br /><br /><br /><br />
    <br /><br /><br /><br />
<footer class="footer-distributed">

			<div class="footer-left">

				<h3>FOSPC<span> TDI 202 </span></h3>

				<p class="footer-links">
					<a href="default.aspx">Home</a>
					·
					<a href="class.aspx">Classes</a>
					·
					<a href="lvr.aspx">Livres</a>
					·
					<a href="stg.aspx">Stagiaires</a>
					·
					<a href="pre.aspx">Prets</a>
				</p>

				<p class="footer-company-name"> OFPPT &copy; 2016</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>ISTA Agadir</span> Agadir, Morocco</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>+212 6-6666-6666</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:soufiane.arbib.95@gmail.com">tdi@gmail.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>About Us</span>
					Just developpers  AKA 'crazy people with great mind' 
				</p>

				<div class="footer-icons">
					<a href="https://www.facebook.com/arbib.soufiane"><i class="fa fa-facebook"></i></a>
					<a href="https://twitter.com/soufianearbib"><i class="fa fa-twitter"></i></a>
					<a href="https://www.linkedin.com/in/soufiane-arbib-975831103"><i class="fa fa-linkedin"></i></a>
					<a href="https://github.com/FOSPC"><i class="fa fa-github"></i></a>
				</div>

			</div>
<div class="col-ms-12 red">dsdf</div>
		</footer> 