<title></title>
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta name="description" content="tdi 202" />
<meta name="author" content="tdi 202"/>
<link href="assets/css/bootstrap.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="assets/css/demo.css"/>
<link rel="stylesheet" href="assets/css/footer-distributed-with-address-and-phones.css"/>
<link href="assets/css/font-awesome.min.css" rel="stylesheet"/>
<link href="assets/css/style.css" rel="stylesheet"/>
<link href="assets/w3/w3.css" rel="stylesheet"/>
<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css"/>