<div class="jumbotron grey" style="border-radius: 20px;padding: 20px;">
	<form role="form" action="system/actions/subscribe/subscribe.php" method="post" name="sub" id="sub">
		<div class="form-group">
			<label class="label-controle" style="color:white">Email:</label>
			<input class="form-control" placeholder="saisir votre email..." type="email" id="email" name="email" required autofocus="yes" />
		</div>
		<div class="form-group">
			<button type="submit" class="btn btn-success btn-md">S'abonner</button>
		</div>
	</form>	
</div>
